
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: postialo-prod
    container_name: postialo-app
    restart: always
    ports:
      - "88:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:18
    container_name: postialo-db
    restart: always
    environment:
      POSTGRES_DB: postialo
      POSTGRES_USER: postialo
      POSTGRES_PASSWORD: Galadriel94*
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
